fl_velocity_controller:
   type: velocity_controllers/JointVelocityController
   joint: forward_left_joint

fl_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

fr_velocity_controller:
   type: velocity_controllers/JointVelocityController
   joint: forward_right_joint

fr_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

bl_velocity_controller:
   type: velocity_controllers/JointVelocityController
   joint: backward_left_joint

bl_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

br_velocity_controller:
   type: velocity_controllers/JointVelocityController
   joint: backward_right_joint

br_joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50